mbit_Robot.CarCtrlSpeed(mbit_Robot.CarState.Car_Run, 255)
basic.pause(100)
mbit_Robot.CarCtrlSpeed(mbit_Robot.CarState.Car_Back, 255)
basic.pause(100)
mbit_Robot.CarCtrlSpeed(mbit_Robot.CarState.Car_Left, 255)
basic.pause(100)
mbit_Robot.CarCtrlSpeed(mbit_Robot.CarState.Car_Right, 255)
basic.pause(100)
